version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:7860"
    environment:
      - CUDA_VISIBLE_DEVICES=
      - HF_TOKEN=${HF_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - APP_USERNAME=${APP_USERNAME}
      - APP_PASSWORD=${APP_PASSWORD}
    volumes:
      - .hf_cache:/app/backend/cache

volumes:
  .hf_cache:
